# Generated by Django 6.0.2 on 2026-02-26 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='max_capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='gymclass',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='gymclass_duration_minutes_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='gymclass',
            constraint=models.CheckConstraint(condition=models.Q(('max_capacity__gte', 1)), name='gymclass_max_capacity_gte_1'),
        ),
    ]
