# Generated by Django 6.0.2 on 2026-03-02 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('classes', '0003_trainer_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='booked_classes', through='bookings.Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
